name: mcdevol_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow-gpu=2.8.1
  - cudatoolkit=10.2
  - pytorch-gpu
  - igraph
  - numpy
  - leidenalg
  - hnswlib
  - pandas
  - tqdm
  - biopython
