name: mcdevol_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - tensorflow=2.8.0
  - tensorflow-base=2.8.0
  - tensorflow-gpu=2.8.0
  - cudatoolkit=11.0
  - cudnn=8.9
  - pytorch-gpu=1.10
  - igraph
  - numpy
  - leidenalg
  - hnswlib
  - pandas
  - tqdm
  - biopython
