name: McDevol

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source $HOME/miniconda/bin/activate
        conda init
    - name: Create Environment
      env:
        CONDA_OVERRIDE_CUDA: "11.0"
      run: |
        conda env create --file environment.yml --name mcdevol_env
        conda activate mcdevol_env
    - name: Verify CUDA Installation
      run: |
        nvcc --version
        nvidia-smi
    - name: Lint with flake8
      run: |
        source $HOME/miniconda/bin/activate mcdevol_env
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda activate mcdevol_env
        conda install pytest
        pytest
